---
title: "Coronavirus Outbreak"
output: 
  flexdashboard::flex_dashboard:
    orientation: row
    vertical_layout: fill
    social: [ "twitter", "facebook", "menu"]
runtime: shiny
---

```{r}
library(flexdashboard)
library(knitr)
library(DT)
library(rpivotTable)
library(ggplot2)
library(plotly)
library(dplyr)
library(openintro)
library(highcharter)
library(ggvis)
library(RCurl)
library(tidyverse)
library(rvest)
library(lubridate)
library(gridExtra)
library(ggthemes)
library(scales)
library(hrbrthemes)
library(countrycode)
library(viridis)
library(shiny)

```


```{r}

####### data scraping ##############
recovered_url<- getURL("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv")
recovered <- read_csv(recovered_url)

confirmed_url <- getURL("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv")
confirmed<- read_csv(confirmed_url)


death_url <- getURL("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv")
death<- read_csv(death_url)

maps_url <- getURL("https://raw.githubusercontent.com/albertyw/avenews/master/old/data/average-latitude-longitude-countries.csv")
maps<- read.csv(text = maps_url)

pop_url <- "https://www.worldometers.info/world-population/population-by-country/"

########################### html tobe replaced with xml2 #########
#pop <- pop_url %>%
#  html() %>%
#  html_nodes(xpath ='//*[@id="example2"]' ) %>%
#  html_table()

#population <- pop[[1]]

################# data cleansing ##############
maps <- maps %>% rename(Code = ISO.3166.Country.Code)

confirmed_data <- confirmed %>% 
  rename(State = "Province/State", Country = "Country/Region", Latitude = Lat, Longitude = Long)%>%
  gather(key= "Date", value = "Count", - c(State,Country,Latitude,Longitude)) %>%
  mutate(Date = gsub("X","",Date),
         Date = gsub("\\.","-",Date),
         Date = mdy(Date)) %>%
  mutate(Country = str_replace_all(Country, "\\*", ""),
         Country = str_replace_all(Country, ", The", ""),
         Country = str_replace_all(Country, "The", ""),
         Country = str_trim(Country)) 

confirmed_data <- confirmed_data[,c(2,1,3,4,5,6)]


recovered_data <- recovered %>% 
rename(State = "Province/State", Country = "Country/Region", Latitude = Lat, Longitude = Long) %>%
  gather(key= "Date", value = "Count", - c(State,Country,Latitude,Longitude)) %>%
    mutate(Date = gsub("X","",Date),
         Date = gsub("\\.","-",Date),
         Date = mdy(Date)) %>%
  mutate(Country = str_replace_all(Country, "\\*", ""),
         Country = str_replace_all(Country, ", The", ""),
         Country = str_replace_all(Country, "The", ""),
         Country = str_trim(Country)) 

recovered_data <- recovered_data[,c(2,1,3,4,5,6)]

death_data <- death %>% 
  rename(State = "Province/State", Country = "Country/Region", Latitude = Lat, Longitude = Long)%>%
  gather(key= "Date", value = "Count", - c(State,Country,Latitude,Longitude)) %>%
    mutate(Date = gsub("X","",Date),
         Date = gsub("\\.","-",Date),
         Date = mdy(Date)) %>%
  mutate(Country = str_replace_all(Country, "\\*", ""),
         Country = str_replace_all(Country, ", The", ""),
         Country = str_replace_all(Country, "The", ""),
         Country = str_trim(Country)) 

death_data <- death_data[,c(2,1,3,4,5,6)]


confirmed_recovered<- confirmed_data %>% 
  full_join(recovered_data,by = c("Country" = "Country","Date" = "Date", "State" = "State","Latitude"= "Latitude", "Longitude"="Longitude"), suffix=c("_confirmed","_recovered"))

full_table <- confirmed_recovered %>% 
  full_join(death_data,by = c("Country" = "Country","Date" = "Date", "State" = "State","Latitude"= "Latitude", "Longitude"="Longitude")) %>%
  rename(recovered = Count_recovered,
         confirmed = Count_confirmed,
         death = Count) %>% 
  mutate(confirmed = replace_na(confirmed,0),
         recovered =replace_na(recovered,0),
         death = replace_na(death,0),
         Country = factor(Country))

####################### data manipulation ###############
gather_table <- full_table %>% 
  gather(key= "Status", value = "Count", - c(Country,State, Latitude, Longitude,Date)) %>% 
  mutate(Count = replace_na(Count,0))

Timelinechart <- gather_table %>% group_by(Date,Status) %>% summarise(Affected = sum(Count)) 

############### chart #############
options(scipen = 999)

#Timeline <- ggplot(Timelinechart, aes(x=Date, y=Affected)) +
#  geom_line(aes(color = Status),na.rm = T) + 
#  (scale_x_date(breaks=date_breaks("14 days"),
#                labels=date_format("%b %d")))+
#  geom_point(aes(color = Status),na.rm = T) +
#  scale_color_manual(values=c("#F4D03F", "#EC7063", "#58D68D"))+
#  xlab("Timeline")
#p <- ggplotly(Timeline) %>% layout(xaxis=list(fixedrange=TRUE)) %>% layout(yaxis=list(fixedrange=TRUE))

  
p <- hchart(Timelinechart, "line", hcaes(x = Date, y = Affected, group = Status)) %>% hc_title(text = "Outbreak Timeline",
           margin = 20, align = "center",
           style = list( useHTML = TRUE))

p <- p %>% hc_add_theme(hc_theme_smpl())

########## Latest Data ############
latest_data<- Timelinechart %>% spread(Status,Affected) %>% arrange(desc(Date)) %>% head(1)
latest_recdata<- Timelinechart %>% spread(Status,Affected) %>% arrange(desc(recovered)) %>% head(1)
latest_recdate <- latest_data$Date


latest_date <- latest_data$Date
latest_Confirmed <- latest_data$confirmed
latest_Death <- latest_data$death
latest_Recovered <- latest_recdata$recovered
fatality <- sprintf("%.2f %%",100*(latest_Death/latest_Confirmed))

new_data_country <- full_table %>% filter(Date == latest_date)%>% group_by(Country) %>%
  summarise(confirmed = sum(confirmed),
            death = sum(death),
            recovered = sum(recovered)) %>% mutate(iso3 = countrycode(Country, origin = 'country.name', destination = 'iso3c'))

all_ctry <- new_data_country %>% select(c(1,2,4,3)) %>% rename(Confirmed = confirmed, Recovered = recovered, Death = death) %>% filter(Confirmed+Recovered+Death > 0 )

affected_countries <- all_ctry %>% 
  mutate(total=Confirmed+Recovered+Death) %>% 
  filter(total >0) %>%
  group_by(Country) %>% count(Country) %>% 
  mutate(n = 1) %>%
  ungroup() %>%
  summarise(total = sum(n))


daily_change <- Timelinechart %>%
  ungroup() %>%
  filter(Status =="confirmed") %>% 
  arrange(desc(Date)) %>% 
  head(3) %>%
  mutate(last_day=lead(Affected),
         Change = (Affected - last_day)/last_day) %>%
  select(Change) %>% head(2)

today_change <- daily_change$Change[1]
yday_change <- daily_change$Change[2]
dailychange <- sprintf("%.2f %%",100*today_change)

daily_change_full <- Timelinechart %>%
  ungroup() %>%
  filter(Status =="confirmed") %>% 
  arrange(desc(Date)) %>% 
  mutate(last_day=lead(Affected),
         Change = (Affected - last_day)/last_day) %>%
  select(Date,Change) %>% mutate(Change = replace_na(Change,0) ,
                                 Change = as.numeric(sprintf("%.2f ",100*(Change))))


  
p2 <- hchart(daily_change_full, "line", hcaes(x = Date, y = Change)) %>% hc_title(text = "Daily Change in Confirmed Cases (%)",
           margin = 20, align = "center",
           style = list( useHTML = TRUE))

p2 <- p2 %>% hc_add_theme(hc_theme_smpl())

```

```{r}
mycolors <- c("blue", "#FFC125", "darkgreen", "darkorange")
```

World
=====================================

Row
-------------------------------------

### Confirmed Cases

```{r}
valueBox(latest_Confirmed,
         icon = "fas fa-hospital",
         color = "#F4D03F")
```

### Recovered

```{r}
valueBox(latest_Recovered,
         caption = "Recovered",
         icon = "fas fa-heartbeat",
         color = "#58D68D")
```


### Dead

```{r}
valueBox(latest_Death,
         icon = "fas fa-exclamation-triangle",
         color = "#EC7063")
```


### Daily Change

```{r}
valueBox(value = dailychange,
         color = ifelse(today_change > yday_change, "red","green"),
         icon = ifelse(today_change > yday_change, "fas fa-arrow-up","fas fa-arrow-down"))
```

### Fatality Rate

```{r}
valueBox(fatality,
         color = "warning",
         icon = "fa-percent")
```

### Affected Countries

```{r}
valueBox(affected_countries,
         color ="#AEB6BF",
         icon = "fas fa-globe")
```




Row
-------------------------------------

```{r}

p

p2
```



Map
=====================================

### MAPS

```{r}


highchart() %>% 
  hc_add_series_map(worldgeojson,new_data_country,
                    name = "Country",
                    value = "confirmed",
                    joinBy = "iso3") %>%
  hc_mapNavigation(enabled = T) %>%
    hc_colorAxis(stops = color_stops(10, rev(inferno(n=10,begin =0.1))))

  #hc_colorAxis(stops = color_stops(10, rev(inferno(n=10,direction = -1,alpha = 1,begin =0.2))))
   #hc_colorAxis(stops = color_stops(10, rev(inferno(10))))


```



Country
==================================


```{r}

ctry_spread <- gather_table %>%
  select(Country, Date, Status, Count)%>% group_by(Country,Date,Status) %>% 
  summarise(Affected = sum(Count)) 

selectInput('ctryInput', 'Country', choices = ctry_spread$Country, selected = as.factor("US"))

```

Row
-----------------------------------------------------------------------

```{r}




latest_ctryConfirmed <- reactive({
  ctry_spread %>%
  spread(key = Status, value = Affected) %>%
  filter(Country == input$ctryInput) %>% 
  arrange(desc(Date)) %>% 
  head(1) %>% ungroup()
})



latest_ctryrecovered <- reactive({
  ctry_spread %>%
  spread(key = Status, value = Affected) %>%
  filter(Country == input$ctryInput) %>% 
  arrange(desc(recovered)) %>% 
  head(1) %>% ungroup() %>%
  select(recovered) %>% pull()
})

latest_ctryfatal <- reactive({
  ctry_spread %>%
  spread(key = Status, value = Affected) %>%
  filter(Country == input$ctryInput) %>% 
  arrange(desc(Date)) %>% 
  mutate(fatal = death/confirmed) %>%
  head(1) %>% ungroup() %>%
  select(fatal) %>% pull()
})

dataset <- reactive({
   ctry_spread %>% filter(Country == input$ctryInput)
})

daily_change_ctry <- reactive({
  ctry_spread %>%
  ungroup() %>%
  filter(Status =="confirmed", Country == input$ctryInput) %>% 
  group_by(Country) %>%
  arrange(desc(Date)) %>% 
  mutate(last_day=lead(Affected),
         last_day = replace_na(last_day,0)) %>%
  mutate(Change = (Affected - last_day)/last_day)%>% 
  mutate(Change = replace_na(Change,0),
         Change = ifelse(Change == Inf, 0, Change),
         Change = as.numeric(sprintf("%.2f ",100*(Change))))
})

today_change_ctry <- reactive({
  ctry_spread %>%
  ungroup() %>%
  filter(Status =="confirmed", Country == input$ctryInput) %>% 
  group_by(Country) %>%
  arrange(desc(Date)) %>% 
  mutate(last_day=lead(Affected),
         last_day = replace_na(last_day,0)) %>%
  mutate(Change = (Affected - last_day)/last_day)%>% 
  mutate(Change = replace_na(Change,0),
         Change = ifelse(Change == Inf, 0, Change),
         Change = as.numeric(sprintf("%.2f ",100*(Change)))) %>%
    ungroup() %>%
    select(Change) %>%
    head(1) %>% 
    pull()
})

yday_change_ctry <- reactive({
  ctry_spread %>%
  ungroup() %>%
  filter(Status =="confirmed", Country == input$ctryInput) %>% 
  group_by(Country) %>%
  arrange(desc(Date)) %>% 
  mutate(last_day=lead(Affected),
         last_day = replace_na(last_day,0)) %>%
  mutate(Change = (Affected - last_day)/last_day)%>% 
  mutate(Change = replace_na(Change,0),
         Change = ifelse(Change == Inf, 0, Change),
         Change = as.numeric(sprintf("%.2f ",100*(Change)))) %>%
    ungroup() %>%
    head(2) %>%
    arrange(Date) %>% 
    select(Change) %>%
    head(1) %>%
    pull()
})

```



### Confirmed Cases {.value-box}

```{r}
renderValueBox({
  
  ctryconfirm <- latest_ctryConfirmed()
  valueBox(
    value = ctryconfirm[3],
    icon = "fas fa-hospital",
    color = "#F4D03F"
  )
})

```

### Recovered {.value-box}

```{r}
renderValueBox({
  
  ctryrecovered <- latest_ctryrecovered()
  valueBox(
    value = ctryrecovered,
    icon = "fas fa-heartbeat",
    color = "#58D68D"
  )
})

```

### Dead {.value-box}

```{r}
renderValueBox({
  
  ctrydead <- latest_ctryConfirmed()
  valueBox(
    value = ctrydead[4],
    icon = "fas fa-exclamation-triangle",
    color = "#EC7063"
  )
})

```

### Daily Change {.value-box}

```{r}
renderValueBox({
  
  today_change_ctry <- today_change_ctry()
  yday_change_ctry <- yday_change_ctry()
  
valueBox(value = sprintf("%.2f %%",today_change_ctry),
         color = ifelse(today_change_ctry > yday_change_ctry, "red","green"),
         icon = ifelse(today_change_ctry > yday_change_ctry, "fas fa-arrow-up","fas fa-arrow-down"))
})
```

### Fatality Rate {.value-box}

```{r}
renderValueBox({
  
  pick <- latest_ctryfatal()
  ctryfatal <- sprintf("%.2f %%",100*pick)
  
valueBox(value = ctryfatal,
         color = "warning",
         icon = "fa-percent")
})
```


Row
----------------------------------------------------------

```{r}
  renderHighchart({
    h1<- hchart(dataset(), "line", hcaes(x = Date, y = Affected, group = Status)) %>% hc_title(text = "Outbreak Timeline",
           margin = 20, align = "center",
           style = list( useHTML = TRUE))
    
    h1 <-h1 %>% hc_add_theme(hc_theme_smpl())


  print(h1)
  
  })

  renderHighchart({
    
    h2 <- hchart(daily_change_ctry(), "line", hcaes(x = Date, y = Change)) %>% hc_title(text = "Daily Change in Confirmed Cases (%)",
           margin = 20, align = "center",
           style = list( useHTML = TRUE))

h2 <- h2 %>% hc_add_theme(hc_theme_smpl())


  print(h2)
})
```




Table
=====================================
  
  
```{r}



datatable(all_ctry, 
          caption = "Latest data by country",
          class = 'cell-border stripe',
          rownames = T,
          options = list (pageLength = 50,dom = 'tip'))

```


About
=====================================

### Information

Data Sources: [Github Data Source](https://github.com/CSSEGISandData/COVID-19)

